---
- hosts: localhost
  connection: local
  become: yes # sudo equivalent

  tasks:
    - import_tasks: tasks/essential.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/nerd-fonts.yml
    - import_tasks: tasks/astro-vim.yml

