---
- name: Installing AstroNvim requirements
  ansible.builtin.package:
    name: 
      - ripgrep
    state: latest


- name: Download AstroNvim
  # Set the correct permissions to the cloned directory
  become: true 
  become_user: manquito
  ansible.builtin.git:
    repo: https://github.com/AstroNvim/AstroNvim
    dest: /home/manquito/.config/nvim
    clone: true
    update: true

- name: Install AstroNvim
  ansible.builtin.shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
