- name: Update packages
  ansible.builtin.apt:
    update-cache: true
    upgrade: true

- name: Install essential packages
  ansible.builtin.package:
    name:
      - vim
      - htop
      - tmux
      - neofetch
    state: latest

- name: Install github3 library
  ansible.builtin.pip:
    name:
      - github3.py
    state: latest
