- name: Update packages
  apt : 
    update-cache: yes
    upgrade: yes  

- name: Install essential packages
  package:
    name: 
      - vim 
      - htop
      - tmux
      - neofetch
    state: latest

- name: Install github3 library
  pip:
    name:
      - github3.py
    state: latest

