---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Lint yml files
    runs-on: ubuntu-latest

  steps: 
      uses: actions/checkout@v2

    - name: Setup python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yamllint and ansible-lint
      run: pip3 install yamllint ansible-lint

    - name: Run yamllint
      run: yamllint .

    - name: Run ansible-lint
      run: ansible-lint -p .


